### ISSUE TITLE
ArgumentError expected a EMLX tensor got Reference

### ISSUE THREAD

**Issue by aymanosman** [elixir-nx/emlx#57]
I get the following error

```
** (ArgumentError) expected a EMLX tensor, got: #Reference<0.2181762389.485621763.191647>
    (emlx 0.1.0) lib/emlx.ex:299: anonymous fn/2 in EMLX.prepare_tensors!/1
    (elixir 1.17.2) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (emlx 0.1.0) lib/emlx.ex:308: EMLX.eval/1
    (emlx 0.1.0) lib/emlx.ex:340: anonymous fn/1 in EMLX.__jit__/5
    (nx 0.9.2) lib/nx/defn/composite.ex:104: anonymous fn/3 in Nx.Defn.Composite.traverse/2
    (nx 0.9.2) lib/nx/container.ex:139: anonymous fn/3 in Nx.Container.Map.traverse/3
    (elixir 1.17.2) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    #cell:gi6wbp26gm726ex4:5: (file)
```

When I run this script: https://gist.github.com/aymanosman/d95ae22934dd8a3f2e7c7506c3b963a0

**Comment by aymanosman** [comment]
It works!
