### ISSUE TITLE
Type mismatch when running Axon with convolutions

### ISSUE THREAD

**Issue by costaraphael** [elixir-nx/emlx#59]
Hey folks! First of all thank you so much for putting this out! I've tested it in a lot of stuff and it is great to see the GPU graph filling up ❤️ 

When running Axon using EMLX backend for regular dense networks, I had zero issues, in fact a performance boost compared to EXLA for large input/param sizes. However when trying to run a convolutional network I get this error during the training stage:

```
** (RuntimeError) type mismatch in EMLX: expected {:s, 32}, got: {:f, 32}. Please report this bug
    (emlx 0.1.0) lib/emlx/backend.ex:372: EMLX.Backend.check_shape_and_type!/3
    (emlx 0.1.0) lib/emlx/backend.ex:41: EMLX.Backend.to_nx/2
    (emlx 0.1.0) lib/emlx/backend.ex:1312: anonymous fn/4 in EMLX.Backend.window_scatter_function/7
    (emlx 0.1.0) lib/emlx/backend.ex:1339: anonymous fn/4 in EMLX.Backend.window_scatter_function/7
    (elixir 1.17.2) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (emlx 0.1.0) lib/emlx/backend.ex:1335: EMLX.Backend.window_scatter_function/7
    (nx 0.9.2) lib/nx/defn/evaluator.ex:441: Nx.Defn.Evaluator.eval_apply/4
    #cell:m3btlngpywal5fd3:5: (file)
```

I set up this small notebook using MNIST to showcase the problem:

<details>

<summary>Notebook</summary>

```elixir
Mix.install([
  {:nx, "~> 0.9.2"},
  {:emlx, github: "elixir-nx/emlx"},
  {:axon, "~> 0.7.0"},
  {:scidata, "~> 0.1.11"}
])
```

```elixir
Nx.default_backend(EMLX.Backend)
```

```elixir
{images, labels} = Scidata.MNIST.download()

{image_data, image_type, image_shape} = images

image_data =
  image_data
  |> Nx.from_binary(image_type)
  |> Nx.divide(255)
  |> Nx.reshape(image_shape, names: [:batch, :channel, :height, :width])
  |> Nx.transpose(axes: [:batch, :height, :width, :channel])

{label_data, label_type, label_shape} = labels

label_data =
  label_data
  |> Nx.from_binary(label_type)
  |> Nx.reshape(label_shape)
  |> Nx.new_axis(-1)
  |> Nx.equal(Nx.iota({10}))

train_range = 0..49_999//1
test_range = 50_000..-1//1

train_images = image_data[train_range]
train_labels = label_data[train_range]

test_images = image_data[test_range]
test_labels = label_data[test_range]

batch_size = 64

train_data =
  train_images
  |> Nx.to_batched(batch_size)
  |> Stream.zip(Nx.to_batched(train_labels, batch_size))

test_data =
  test_images
  |> Nx.to_batched(batch_size)
  |> Stream.zip(Nx.to_batched(test_labels, batch_size))
```

```elixir
model =
  Axon.input("images", shape: {nil, 28, 28, 1})
  |> Axon.conv(32, kernel_size: {3, 3}, padding: :same, activation: :relu)
  |> Axon.batch_norm()
  |> Axon.max_pool(kernel_size: {2, 2}, strides: [2, 2])
  |> Axon.flatten()
  |> Axon.dense(128, activation: :relu)
  |> Axon.dense(10, activation: :softmax)
```

```elixir
trained_model_state =
  model
  |> Axon.Loop.trainer(:categorical_cross_entropy, Polaris.Optimizers.adam())
  |> Axon.Loop.metric(:accuracy, "accuracy")
  |> Axon.Loop.run(train_data, Axon.ModelState.empty(), epochs: 20)
```
</details>

I did a little bit of digging, and it seems like the `window_scatter_function` runs twice, the first time succeeds and the second time we get the type mismatch error, so maybe the first run is returning the wrong type which is fed to itself again later?

I know that `Nx.conv` is working nicely, so the problem is somewhere between a single convolution and training a convolutional network. Sorry for not being able to narrow it down further 😅 

Thanks again and I'll keep having a look at this, even if I don't fix it maybe I'll learn something 😄

**Comment by polvalente** [comment]
@costaraphael I've ran your code locally to ensure things work :)
