### ISSUE TITLE
Interior padding not supported in EMLX

### ISSUE THREAD

**Issue by ndrean** [elixir-nx/emlx#64]
```elixir
t = Nx.tensor([1,2,3])
one_zero_left = Nx.pad(t, 0, [{1,0,0}])
# [0, 1, 2, 3] :ok
two_5_right = Nx.pad(t, 5, [{0,2,0}])
# [1, 2, 3, 5, 5] :ok
spaced_with_three_five_from_left = Nx.pad(t, 5, [{1, 0, 3}])

Shape mismatch in MLX array conversion:
Expected shape: {10}
Got shape: {4}

    (emlx 0.1.0) lib/emlx/backend.ex:360: EMLX.Backend.check_shape_and_type!/3
    (emlx 0.1.0) lib/emlx/backend.ex:53: EMLX.Backend.to_nx/2
    (nx 0.9.2) lib/nx.ex:5408: Nx.apply_vectorized/2
```

**Comment by polvalente** [comment]
I've updated main with a better error message, but the fact is that interior padding is not yet supported in Nx.pad.
Adding this will also unlock the ability to do dilations in window_* functions
