### ISSUE TITLE
EMLX.Backend.check_shape_and_type produces mismatch error

### ISSUE THREAD

**Issue by VladMyh** [elixir-nx/emlx#69]
Hi, 
I'm trying to run image recognition with [resnet-18](https://huggingface.co/microsoft/resnet-18) but I'm getting error from EMLX.Backend.check_shape_and_type!/3

```
** (ArgumentError) Shape mismatch in MLX array conversion:
Expected shape: {1, 224, 224, 3}
Got shape: {1, 256, 256, 3}

    (emlx 0.1.0) lib/emlx/backend.ex:364: EMLX.Backend.check_shape_and_type!/3
    (emlx 0.1.0) lib/emlx/backend.ex:53: EMLX.Backend.to_nx/2
    (nx 0.9.2) lib/nx.ex:5408: Nx.apply_vectorized/2
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (bumblebee 0.6.0) lib/bumblebee/vision/convnext_featurizer.ex:66: Bumblebee.Vision.ConvNextFeaturizer.process_input/2
    (bumblebee 0.6.0) lib/bumblebee/vision/image_classification.ex:68: anonymous fn/2 in Bumblebee.Vision.ImageClassification.image_classification/3
    (nx 0.9.2) lib/nx/serving.ex:1747: anonymous fn/3 in Nx.Serving.handle_preprocessing/2
```

This is what I tries so far:
* IO.inspect before calling `run` tensor looks to be correct shape u8[224][224][3]
* With `IEx.break!(EMLX.Backend, :check_shape_and_type!, 3)` when I reach line 363 actual_shape and expected_shape have the same value

Is there something else I can check or debug?

Thank you!

My code
```
# Install deps
Mix.install([
  {:bumblebee, github: "elixir-nx/bumblebee", override: true},
  {:emlx, github: "elixir-nx/emlx"},
  {:kino_bumblebee, "~> 0.5.1"},
  {:vix, "~> 0.31.1"}
])

# Set defaults
Nx.global_default_backend({EMLX.Backend, device: :gpu})
Nx.Defn.default_options(compiler: EMLX)
    
# Load model
model_name = "microsoft/resnet-18"
{:ok, model} = Bumblebee.load_model({:hf, model_name})
{:ok, featurizer} = Bumblebee.load_featurizer({:hf, model_name})
serving = Bumblebee.Vision.image_classification(model, featurizer)
    
{:ok, image} = Vix.Vips.Image.new_from_file("bird-original.jpg")
{:ok, resized_image} = Vix.Vips.Operation.resize(image, 0.207)
{:ok, %{data: data, shape: shape, type: type}} = Vix.Vips.Image.write_to_tensor(resized_image)
    
IO.inspect(shape)
    
image = data
  |> Nx.from_binary(:u8)
  |> Nx.reshape({224, 224, 3})
  |> IO.inspect()
    
Nx.Serving.run(serving, image)   
```

What I get in iex debug
```
Break reached: EMLX.Backend.check_shape_and_type!/3 (/Users/vladmihajlenko/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1.2/91b202b0ba401bded5d629302b092989/deps/emlx/lib/emlx/backend.ex:363)

  360:     actual_shape = EMLX.shape(device_ref)
  361:     actual_type = EMLX.scalar_type(device_ref) |> to_nx_type()
  362:
  363:     if actual_shape != expected_shape do
  364:       raise ArgumentError, """
  365:       Shape mismatch in MLX array conversion:
  366:       Expected shape: #{inspect(expected_shape)}

iex(177)> actual_shape
{512}
iex(178)> expected_shape
{512}
iex(179)> n
Break reached: EMLX.Backend.check_shape_and_type!/3 (/Users/vladmihajlenko/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1.2/91b202b0ba401bded5d629302b092989/deps/emlx/lib/emlx/backend.ex:371)

  368:       """
  369:     end
  370:
  371:     case {actual_type, expected_type} do
  372:       {{:s, 8}, {:s, qint}} when qint in [2, 4] ->
  373:         :ok
  374:

iex(180)> n
Break reached: EMLX.Backend.check_shape_and_type!/3 (/Users/vladmihajlenko/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1.2/91b202b0ba401bded5d629302b092989/deps/emlx/lib/emlx/backend.ex:395)

  392:         :ok
  393:     end
  394:
  395:     device_ref
  396:   end
  397:
  398:   @impl true

iex(181)> n
** (ArgumentError) Shape mismatch in MLX array conversion:
Expected shape: {1, 224, 224, 3}
Got shape: {1, 256, 256, 3}

    (emlx 0.1.0) lib/emlx/backend.ex:364: EMLX.Backend.check_shape_and_type!/3
    (emlx 0.1.0) lib/emlx/backend.ex:53: EMLX.Backend.to_nx/2
    (nx 0.9.2) lib/nx.ex:5408: Nx.apply_vectorized/2
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (bumblebee 0.6.0) lib/bumblebee/vision/convnext_featurizer.ex:66: Bumblebee.Vision.ConvNextFeaturizer.process_input/2
    (bumblebee 0.6.0) lib/bumblebee/vision/image_classification.ex:68: anonymous fn/2 in Bumblebee.Vision.ImageClassification.image_classification/3
    (nx 0.9.2) lib/nx/serving.ex:1747: anonymous fn/3 in Nx.Serving.handle_preprocessing/2
```

**Comment by polvalente** [comment]
Does the code run with EXLA?

**Comment by polvalente** [comment]
I believe if you can add a breakpoint where I have the `dbg` call below, in Nx.Defn.Evaluator, we'll be able to pinpoint the problem more easily. If we get the full Nx.Defn.Expr inspect result, it should be easier to pinpoint which EMLX functions are being called, and therefore, where the shape mismatch is happening.

```elixir
  @impl true
  def __compile__(_key, vars, fun, opts) do
    hooks = Keyword.get(opts, :hooks, %{})
    gc? = Keyword.get(opts, :garbage_collect, false)
    {expr, output, cache} = precompile(fun, vars, hooks)
    
    #### ADD THIS
    dbg(expr, limit: :infinity)
    ####

    fn [params] ->
      [
        expr
        |> composite_eval(%{params: params, gc: gc?}, [cache])
        |> apply_output(output)
      ]
    end
  end
```

**Comment by VladMyh** [comment]
When I run with EXLA it works, [livebook link](https://gist.github.com/VladMyh/474f8be792e798d33d54c45859728e40). I also tried with EMLX cpu backend I get same error.

debug:
```elixir
Break reached: Nx.Defn.Evaluator.__compile__/4 (/Users/vladmihajlenko/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1.2/91b202b0ba401bded5d629302b092989/deps/nx/lib/nx/defn/evaluator.ex:67)

   64:     gc? = Keyword.get(opts, :garbage_collect, false)
   65:     {expr, output, cache} = precompile(fun, vars, hooks)
   66:
   67:     fn [params] ->
   68:       [
   69:         expr
   70:         |> composite_eval(%{params: params, gc: gc?}, [cache])

iex(198)> dbg(expr, limit: :infinity)
[(nx 0.9.2) /Users/vladmihajlenko/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1.2/91b202b0ba401bded5d629302b092989/deps/nx/lib/nx/defn/evaluator.ex:198: Nx.Defn.Evaluator.__compile__/4]
expr #=> #Nx.Tensor<
  u8[batch: 1][224][224][3]

  Nx.Defn.Expr
  parameter a:0   u8[224][224][3]
  b = reshape a   u8[1][224][224][3]
>

#Nx.Tensor<
  u8[batch: 1][224][224][3]

  Nx.Defn.Expr
  parameter a:0   u8[224][224][3]
  b = reshape a   u8[1][224][224][3]
>
```

**Comment by polvalente** [comment]
Can you share the image used so I can run this locally. It's a bit weird that a single reshape is causing the issue.

**Comment by VladMyh** [comment]
Here is the [image](https://github.com/VladMyh/EMLX-Livebook/blob/main/bird-original.jpg), I also pushed my livebooks [here](https://github.com/VladMyh/EMLX-Livebook), [emlx-test.livemd](https://github.com/VladMyh/EMLX-Livebook/blob/main/emlx-test.livemd) is the original EMLX version, [emlx-test-fork.livemd](https://github.com/VladMyh/EMLX-Livebook/blob/main/emlx-test-fork.livemd) is EXLA version.
I tried different images with EXLA version they all work, EMLX version same error.

**Comment by polvalente** [comment]
Thank you. I asked about EXLA just to rule out any possible issues in Bumblebee itself.

This is most likely some wrong conversion from mlx to Nx somewhere along the oath that's exploding in the following function call.

**Comment by polvalente** [comment]
I found the problem. Bumblebee is making use of negative pads as slices, and EMLX doesn't support that yet.

Should be an easy fix

**Comment by polvalente** [comment]
I ran your livebook locally and it passed. Feel free to reopen if it doesn't work for any reason

**Comment by VladMyh** [comment]
Great, thank you!
